version: '3.2'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./docker/app.Dockerfile
    restart: always
    depends_on:
      - elasticsearch
      - kibana

  api:
    container_name: api
    build: 
      context: .
      dockerfile: ./docker/api.Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - app

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5.6-alpine
    restart: always
    environment:
      cluster.name: docker-cluster
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      -  elasticsearch-data:/var/lib/elasticsearch
 
  kibana:
    container_name: kibana
    image: kibana:5.6
    restart: always
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - "5601:5601"

volumes:
  elasticsearch-data: